"""
test_formatters.py — Tests for utils/formatters.py

Covers: JSON export, plain text structure, summary generation,
empty data handling, and unicode.
"""

import json
import pytest
from utils.formatters import itinerary_to_json, itinerary_to_text, itinerary_to_summary


def _sample():
    return {
        "destination": "Kyoto, Japan",
        "trip_length_days": 2,
        "budget_level": "Moderate",
        "travel_style": ["Culinary", "Culture"],
        "interests": ["Temples", "Street Food"],
        "pace": "Balanced",
        "summary": "A lovely trip to Kyoto.",
        "estimated_total_cost": 300,
        "daily_cost_average": 150,
        "days": [
            {
                "day_number": 1,
                "theme": "Historic Kyoto",
                "estimated_day_cost": 140,
                "items": [
                    {"time_block": "Morning", "title": "Fushimi Inari", "type": "activity", "description": "Gates.", "estimated_cost": 0, "location_name": "FI"},
                    {"time_block": "Lunch", "title": "Nishiki Market", "type": "meal", "description": "Food.", "estimated_cost": 18, "location_name": "NM"},
                ],
            },
            {
                "day_number": 2,
                "theme": "Arashiyama",
                "estimated_day_cost": 160,
                "items": [
                    {"time_block": "Morning", "title": "Bamboo Grove", "type": "activity", "description": "Bamboo.", "estimated_cost": 0, "location_name": "BG"},
                ],
            },
        ],
    }


class TestJsonExport:
    def test_valid_json(self):
        parsed = json.loads(itinerary_to_json(_sample()))
        assert parsed["destination"] == "Kyoto, Japan"

    def test_pretty_printed(self):
        assert "\n" in itinerary_to_json(_sample())

    def test_unicode_preserved(self):
        s = _sample()
        s["destination"] = "日本、京都"
        assert "日本" in itinerary_to_json(s)


class TestTextExport:
    def test_header(self):
        t = itinerary_to_text(_sample())
        assert "TRIPSKETCH AI" in t
        assert "KYOTO, JAPAN" in t

    def test_summary(self):
        assert "A lovely trip" in itinerary_to_text(_sample())

    def test_cost_overview(self):
        t = itinerary_to_text(_sample())
        assert "300" in t
        assert "150" in t

    def test_day_headers(self):
        t = itinerary_to_text(_sample())
        assert "DAY 1" in t
        assert "DAY 2" in t
        assert "Historic Kyoto" in t

    def test_items_present(self):
        t = itinerary_to_text(_sample())
        assert "Fushimi Inari" in t
        assert "Nishiki Market" in t

    def test_free_items(self):
        assert "Free" in itinerary_to_text(_sample())

    def test_meal_icon(self):
        assert "🍽" in itinerary_to_text(_sample())

    def test_footer(self):
        assert "Generated by TripSketch AI" in itinerary_to_text(_sample())


class TestSummaryExport:
    def test_contains_destination(self):
        assert "Kyoto, Japan" in itinerary_to_summary(_sample())

    def test_contains_cost(self):
        assert "300" in itinerary_to_summary(_sample())

    def test_contains_day_count(self):
        assert "2 days" in itinerary_to_summary(_sample())


class TestEdgeCases:
    def test_empty_days(self):
        s = _sample()
        s["days"] = []
        assert "TRIPSKETCH AI" in itinerary_to_text(s)

    def test_missing_summary(self):
        s = _sample()
        del s["summary"]
        assert "TRIPSKETCH AI" in itinerary_to_text(s)

    def test_empty_itinerary_json(self):
        assert json.loads(itinerary_to_json({})) == {}
