"""
formatters.py — Export formatters for itinerary data.

Provides JSON serialization and a human-readable plain-text format
grouped by day, suitable for copying into notes or emails.
"""

from __future__ import annotations

import json


def itinerary_to_json(itinerary: dict) -> str:
    """Serialize itinerary dict to pretty-printed JSON string."""
    return json.dumps(itinerary, indent=2, ensure_ascii=False)


def itinerary_to_text(itinerary: dict) -> str:
    """
    Convert itinerary dict to a readable plain-text format grouped by day.

    Output structure:
      - Header with destination and summary
      - Cost overview
      - Day-by-day sections with items grouped by time block
      - Footer
    """
    lines = []
    dest = itinerary.get("destination", "Unknown")

    # --- Header ---
    lines.append("=" * 60)
    lines.append(f"  TRIPSKETCH AI — {dest.upper()}")
    lines.append("=" * 60)
    lines.append("")

    summary = itinerary.get("summary", "")
    if summary:
        lines.append(summary)
        lines.append("")

    # --- Cost overview ---
    budget = itinerary.get("budget_level", "N/A")
    pace = itinerary.get("pace", "N/A")
    style = itinerary.get("travel_style", [])
    style_str = ", ".join(style) if isinstance(style, list) else str(style)

    lines.append(f"Budget: {budget}  |  Style: {style_str}  |  Pace: {pace}")
    lines.append(
        f"Estimated total: ${itinerary.get('estimated_total_cost', 0):,.0f} USD"
    )
    lines.append(
        f"Average per day: ${itinerary.get('daily_cost_average', 0):,.0f} USD"
    )
    lines.append("")

    # --- Day-by-day ---
    for day in itinerary.get("days", []):
        day_num = day.get("day_number", "?")
        theme = day.get("theme", "")
        day_cost = day.get("estimated_day_cost", 0)

        lines.append("-" * 60)
        lines.append(f"DAY {day_num}: {theme}")
        lines.append(f"Estimated day cost: ${day_cost:,.0f}")
        lines.append("")

        for item in day.get("items", []):
            block = item.get("time_block", "")
            title = item.get("title", "Untitled")
            cost = item.get("estimated_cost", 0)
            cost_str = "Free" if cost == 0 else f"~${cost:,.0f}"
            item_type = item.get("type", "activity")
            desc = item.get("description", "")

            type_icon = "🍽" if item_type == "meal" else "📍"
            lines.append(f"  [{block}] {type_icon} {title} ({cost_str})")
            if desc:
                lines.append(f"           {desc}")
            lines.append("")

    # --- Footer ---
    lines.append("=" * 60)
    lines.append("Generated by TripSketch AI")
    lines.append("=" * 60)

    return "\n".join(lines)


def itinerary_to_summary(itinerary: dict) -> str:
    """
    Generate a short copyable summary — a few lines that capture
    the destination, duration, budget, and highlights.
    """
    dest = itinerary.get("destination", "Unknown")
    days = len(itinerary.get("days", []))
    total = itinerary.get("estimated_total_cost", 0)
    budget = itinerary.get("budget_level", "")
    summary = itinerary.get("summary", "")

    text = f"{dest} — {days} days, ${total:,.0f} ({budget})\n\n{summary}"
    return text.strip()
