"""
pdf_export.py — Generate a styled PDF from an itinerary dict.

Uses fpdf2 for lightweight PDF generation with no system dependencies.
"""

from __future__ import annotations

from fpdf import FPDF


def itinerary_to_pdf(itinerary: dict) -> bytes:
    """
    Generate a styled PDF from an itinerary dict.

    Returns the PDF as bytes (ready for st.download_button).
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ---- Title ----
    pdf.set_font("Helvetica", "B", 22)
    dest = itinerary.get("destination", "Trip Itinerary")
    pdf.cell(0, 12, f"TripSketch AI — {dest}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # ---- Summary ----
    summary = itinerary.get("summary", "")
    if summary:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 5, summary)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(4)

    # ---- Trip info line ----
    days = itinerary.get("trip_length_days", "?")
    budget = itinerary.get("budget_level", "?")
    total = itinerary.get("estimated_total_cost", 0)
    avg = itinerary.get("daily_cost_average", 0)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(
        0, 5,
        f"{days} days  |  {budget} budget  |  Est. ${total}  |  ~${avg}/day",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # ---- Divider ----
    _draw_divider(pdf)

    # ---- Days ----
    for day in itinerary.get("days", []):
        day_num = day.get("day_number", "?")
        theme = day.get("theme", "")
        day_cost = day.get("estimated_day_cost", 0)

        # Day header
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, f"Day {day_num}: {theme}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 4, f"Est. ${day_cost}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

        # Group items by time block
        current_block = None
        for item in day.get("items", []):
            time_block = item.get("time_block", "")
            title = item.get("title", "Untitled")
            item_type = item.get("type", "activity")
            description = item.get("description", "")
            cost = item.get("estimated_cost", 0)
            cost_str = f"${cost}" if cost else "Free"

            # Time block header
            if time_block != current_block:
                current_block = time_block
                pdf.ln(2)
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(100, 100, 100)
                pdf.cell(0, 5, time_block.upper(), new_x="LMARGIN", new_y="NEXT")
                pdf.set_text_color(0, 0, 0)

            # Item
            type_label = "MEAL" if item_type == "meal" else "ACTIVITY"
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 6, f"{title}  [{type_label}]", new_x="LMARGIN", new_y="NEXT")

            if description:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(80, 80, 80)
                pdf.multi_cell(0, 4.5, description)
                pdf.set_text_color(0, 0, 0)

            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 4, cost_str, new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
            pdf.ln(2)

        _draw_divider(pdf)

    # ---- Footer ----
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 4, "Generated by TripSketch AI — tripsketch-ai.streamlit.app", new_x="LMARGIN", new_y="NEXT")

    return pdf.output()


def _draw_divider(pdf: FPDF) -> None:
    """Draw a light horizontal line."""
    pdf.set_draw_color(200, 200, 200)
    y = pdf.get_y()
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.ln(4)
